# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pib',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
